### ISSUE TITLE
V7不出检测结果

### ISSUE THREAD

**Issue by Agustinwgq** [positive666/yolov5_research#59]
## ❔Question
你好，我想请问下，我训练完之后，如图所示不显示训练结果是怎么回事呢？
yolov7 summary: 314 layers, 36524924 parameters, 6194944 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|        
Traceback (most recent call last):
  File "train.py", line 734, in <module>
    main(opt)
  File "train.py", line 631, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 518, in train
    results, _, _ = val.run(data_dict,
  File "/home/imcm/anaconda3/envs/yolov5_multi_backbone_train/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/imcm/code/wanggq/yolov5_research-master/val.py", line 209, in run
    out, train_out = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
  File "/home/imcm/anaconda3/envs/yolov5_multi_backbone_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/imcm/code/wanggq/yolov5_research-master/models/yolo.py", line 500, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/imcm/code/wanggq/yolov5_research-master/models/yolo.py", line 523, in _forward_once
    x = m(x)  # run
  File "/home/imcm/anaconda3/envs/yolov5_multi_backbone_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/imcm/code/wanggq/yolov5_research-master/models/yolo.py", line 290, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by Agustinwgq** [comment]
已解决
